---
apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: east
  namespace: east
---
apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: backend
  namespace: east
spec:
  routingKey: backend
  port: 9090
  host: 0.0.0.0
